import "server-only";

import { serverEnvSchema } from "./schema";

export const serverEnv = serverEnvSchema.parse({
  APP_ENV: process.env.APP_ENV,
  HEDERA_NETWORK: process.env.HEDERA_NETWORK,
  HEDERA_OPERATOR_ID: process.env.HEDERA_OPERATOR_ID,
  HEDERA_OPERATOR_KEY: process.env.HEDERA_OPERATOR_KEY,
  HEDERA_RECIPIENT_ID: process.env.HEDERA_RECIPIENT_ID,
  HEDERA_TRANSFER_HBAR: process.env.HEDERA_TRANSFER_HBAR,
  HEDERA_TOPIC_ID: process.env.HEDERA_TOPIC_ID,
  HEDERA_MIRROR_NODE_URL: process.env.HEDERA_MIRROR_NODE_URL,
  HEDERA_PROJECTION_PUBLIC_QUERY_URL:
    process.env.HEDERA_PROJECTION_PUBLIC_QUERY_URL,
  DISCOVERY_SOURCE: process.env.DISCOVERY_SOURCE,
  GRAPH_ENDPOINT: process.env.GRAPH_ENDPOINT,
  GRAPH_DEPLOYMENT_ID: process.env.GRAPH_DEPLOYMENT_ID,
  GRAPH_NETWORK: process.env.GRAPH_NETWORK,
  GRAPH_MAX_STALENESS_MS: process.env.GRAPH_MAX_STALENESS_MS,
  GRAPH_ACCESS_TOKEN: process.env.GRAPH_ACCESS_TOKEN,
  SCALEWAY_GENAI_API_KEY: process.env.SCALEWAY_GENAI_API_KEY,
  SCALEWAY_GENAI_BASE_URL: process.env.SCALEWAY_GENAI_BASE_URL,
  SCALEWAY_GENAI_MODEL: process.env.SCALEWAY_GENAI_MODEL,
  PLANNER_TIMEOUT_MS: process.env.PLANNER_TIMEOUT_MS,
  G_API_KEY_PRIVATE: process.env.G_API_KEY_PRIVATE,
  G_API_KEY_MANAGEMENT: process.env.G_API_KEY_MANAGEMENT,
  ZG_ROUTER_BASE_URL: process.env.ZG_ROUTER_BASE_URL,
  ZG_COMPUTE_MAX_ATTEMPTS: process.env.ZG_COMPUTE_MAX_ATTEMPTS,
  ZG_COMPUTE_TIMEOUT_MS: process.env.ZG_COMPUTE_TIMEOUT_MS,
  SUPABASE_URL: process.env.SUPABASE_URL,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
});
